### ISSUE TITLE
Add Hacktoberfest to topic

### ISSUE THREAD

**Issue by Plingooo** [fharookshaik/fibonacci_series#8]
Hey,
can you please add hacktoberfest to your topic. Otherwise the PRs will not be counted.
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by fharookshaik** [comment]
Sure. Thanks for raising this issue @Plingooo

**Comment by Plingooo** [comment]
perfect, but you still have a typo in the topic. It must be called hac**k**toberfest. :)

**Comment by fharookshaik** [comment]
Hey It's Hacktoberfest only. Anyways I've added all the labels that'll need to accept the hacktoberfest
